application: cakephp-appengine
version: 1
runtime: php
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: app/webroot/css
 
- url: /js
  static_dir: app/webroot/js
 
- url: /img
  static_dir: app/webroot/img
 
- url: /favicon.ico
  static_files: app/webroot/favicon.ico
  upload: app/webroot/favicon.ico
 
- url: /.*
  script: app/webroot/index.php
  
- url: /debug_kit/css
  static_dir: app/Plugin/DebugKit/webroot/css
 
- url: /debug_kit/js
  static_dir: app/Plugin/DebugKit/webroot/js
  
- url: /debug_kit/img
  static_dir: app/Plugin/DebugKit/webroot/img